title: Mr.Brown
description: Mr.Brown is a responsive jekyll theme
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog

sass:
    sass_dir: _sass

# Comments
discus_identifier: mr-brown
txtpen_identifier: raizer85

# Social settings
facebook_url: https://www.facebook.com/alejovicu
linkedin_url: https://www.linkedin.com/in/alejandrorosero
github_url: https://github.com/alejovicu
